### ISSUE TITLE
Additional website/player translations

### ISSUE THREAD

**Issue by baukevanderlaan** [sylvainjule/ethicsfordesign-website#1]
Hello,

I'm working on a Dutch translation for the subtitles and noticed that the website and player itself are available in two languages. Would additional translations for the website and player be useful and/or welcome?

All the best,
Bauke

**Comment by sylvainjule** [comment]
Hello,

So sorry for the delay. Thanks for your proposal, we're keen to keep those two languages for the website itself for now, to keep the maintenance simple for us. But the subtitles translations would be awesome ! :)

**Comment by baukevanderlaan** [comment]
Alright, that's understandable. I'm almost finished with the Dutch subtitles and I'll make a pull request as soon as they're done.
